data_dir: E:/SURF_2/Scripts/R/scripts/BEHAV3D//demos/organoid_demo/data
output_dir: E:/SURF_2/Scripts/R/scripts/BEHAV3D//demos/organoid_demo/example_output
metadata_csv_path: E:/SURF_2/Scripts/R/scripts/BEHAV3D//demos/organoid_demo/BEHAV3D_metadata.tsv
randomforest_path: E:/SURF_2/Scripts/R/scripts/BEHAV3D//references/TrainedRandomForest.Rdata
tcell_exp_duration: 400
tcell_min_track_length: 60
tcell_max_track_length: 60
organoid_min_volume: 1000
organoid_min_track_length: 40
organoid_exp_duration: 300
umap_minimal_distance: 0.1
umap_n_neighbors: 5
nr_of_clusters: 6
